In [1]:
#check greater number between 3 numbers
a=int(input("Enter the value: "))
b=int(input("Enter the value: "))
c=int(input("Enter the value: "))
if a>=b and a>=c:
     print("a is greater ")
elif b>=c and b>=a:
     print("b is greater ")
else:
    print("c is greater ")
    


Enter the value:  45
Enter the value:  78
Enter the value:  96


c is greater 


In [5]:
#nested if 
#check a number is xero or positive or negative

a=int(input("Enter the value: "))
if a>=0:
    if a==0:
        print("The number is zero")
    if a>=0:
        print("The number is positive")
else:
    print("the number is negative")


Enter the value:  90


The number is positive


In [7]:
s=set([3,4,5,6])
print(s)

{3, 4, 5, 6}


In [8]:
a={1,2,3,4,5}
b={4,5,6,7,8}
print(a|b) #union

{1, 2, 3, 4, 5, 6, 7, 8}


In [10]:
a={1,2,3,4,5}
b={4,5,6,7,8}
a.union(b)



{1, 2, 3, 4, 5, 6, 7, 8}

In [11]:
a={1,2,3,4,5}
b={4,5,6,7,8}
print(a&b) #intersection

{4, 5}


In [13]:
a={1,2,3,4,5}
b={4,5,6,7,8}
print(a-b)
print(b-a)

{1, 2, 3}
{8, 6, 7}


In [14]:
a={1,2,3,4,5}
b={4,5,6,7,8}
print(a^b)

{1, 2, 3, 6, 7, 8}


In [19]:
it={"Alice", "Bob", "Charlie", "Vishal"}
csm={"Koushik", "Chandana", "Swathi", "Vishal"}
print("All students enrolled at least one program: ", csm|it)
print("Students who enrolled in both programs:", csm&it)
print("only in csm but not in it:", it-csm)
print("students who are unique:",csm^it)

All students enrolled at least one program:  {'Koushik', 'Swathi', 'Alice', 'Chandana', 'Bob', 'Charlie', 'Vishal'}
Students who enrolled in both programs: {'Vishal'}
only in csm but not in it: {'Alice', 'Bob', 'Charlie'}
students who are unique: {'Alice', 'Koushik', 'Swathi', 'Chandana', 'Bob', 'Charlie'}


In [23]:
a={1,2,3,4,5}
b=a.copy()
print(b)

{1, 2, 3, 4, 5}


In [25]:
a={1,2,3,4,5}
a.add(9)
a

{1, 2, 3, 4, 5, 9}

In [27]:
dictionary={'a':10, 'b': 13, 'c':22}
dictionary

{'a': 10, 'b': 13, 'c': 22}

In [29]:
d={'Name':'Chandana', 'Age': 20, 'Branch':'Csm'}
d['Age']=21  #update
d

{'Name': 'Chandana', 'Age': 21, 'Branch': 'Csm'}

In [34]:
d={'Name':'Chandana', 'Age': 20, 'Branch':'Csm'}
d.clear()
print(d)

{}


In [39]:
d={'Name':'Chandana', 'Age': 20, 'Branch':'Csm'}
print(d['Name'])
print(d['Age'])
print(d['Branch'])
d.items()

Chandana
20
Csm


dict_items([('Name', 'Chandana'), ('Age', 20), ('Branch', 'Csm')])

In [61]:
student_marks={
    "Swathi": 98,
    "Chandana":96,
    "Koushik":58,
    "Bharath":25,
}
print("Names and marks of students", student_marks)
student_marks['Tanvi']= 58
print("updated Names and marks of students", student_marks)
student_marks['Bharath']=76
print("updating Bharath marks:",student_marks)
student_marks.pop('Koushik')
print("After deleting koushik",student_marks)
topper = max(student_marks, key=student_marks.get)
print("Topper is:", topper, "with marks:", student_marks[topper])
average_marks = sum(student_marks.values()) / len(student_marks)
print(f"The average marks are {average_marks:.2f}.")


Names and marks of students {'Swathi': 98, 'Chandana': 96, 'Koushik': 58, 'Bharath': 25}
updated Names and marks of students {'Swathi': 98, 'Chandana': 96, 'Koushik': 58, 'Bharath': 25, 'Tanvi': 58}
updating Bharath marks: {'Swathi': 98, 'Chandana': 96, 'Koushik': 58, 'Bharath': 76, 'Tanvi': 58}
After deleting koushik {'Swathi': 98, 'Chandana': 96, 'Bharath': 76, 'Tanvi': 58}
Topper is: Swathi with marks: 98
The average marks are 82.00.


In [65]:
def add():
    a=190;
    b=890;
    c=a+b;
print("The sum is",c)
add()

The sum is 96


In [67]:
def add(a,b):
    c=a+b;
    print("The sum is",c)
add(865,826)

The sum is 1691


In [73]:
def area():
    l=int(input("Enter the value: "))
    b=int(input("Enter the value: "))
    rec=l*b;
    print("Area of the rectangle",rec)
rectangle=area()


Enter the value:  78
Enter the value:  98


Area of the rectangle 7644


In [74]:
def area(x,y):
    print("Area of the rectangle",x*y)
l=int(input("Enter the value: "))
b=int(input("Enter the value: "))
rectangle=area(l,b)


Enter the value:  78
Enter the value:  90


Area of the rectangle 7020


In [75]:
#factorial
def fact(n):
    sum=1
    for i in range (1,n+1):
        sum*=i
    print(f"Factorial of (n) is {sum}")
n=int(input("Enter the value: "))
fact(n)

Enter the value:  5


Factorial of (n) is 120


In [78]:
def add(a,b):
    c=a+b;
    return c
result= add(10,20);
print(result);

30


In [79]:
#factorial
def fact(n):
    sum=1
    for i in range (1,n+1):
        sum*=i
    return sum
n=int(input("Enter the value: "))
fact(n)

Enter the value:  5


120

In [83]:
def fact():
    n=int(input("Enter the value: "))
    sum=1
    for i in range (1,n+1):
        sum*=i
    return sum
num=fact()
print("the factorial is",num)

Enter the value:  5


the factorial is 120


In [85]:
class emp:
    def empData(self):
        self.eno=111
        self.ename="aaa"
        self.esal=10000
        print("emp number ;",self.eno)
        print("emp name ;",self.ename)
        print("emp salary ;",self.esal)
e=emp()
e.empData()

emp number ; 111
emp name ; aaa
emp salary ; 10000


In [89]:
class emp:
    def getData(self):
        self.eno=int(input("Enter the employee number: "))
        self.ename=input("Enter the employee name: ")
        self.esal=float(input("Enter the employye salary: "))
    def dispdata(self):
        print("emp number :",self.eno)
        print("emp name :",self.ename)
        print("emp salary :",self.esal)
        
e=emp()
e.getData()
e.dispdata()

Enter the employee number:  90
Enter the employee name:  chandana
Enter the employye salary:  10000


emp number : 90
emp name : chandana
emp salary : 10000.0


In [91]:
pip install numpy


In [6]:
import numpy as np
arr_1d=np.array([1,2,3])
print(arr_1d)
arr_2d=np.array([[1,2,3], [4,5,6]])
print(arr_2d)
arr_3d=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_3d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np
arr_3d=np.zeros((2,3))
print(arr_3d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
import numpy as np
arr_3d=np.zeros((3,3))
print(arr_3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
import numpy as np
arr_3d=np.ones((2,3))
print(arr_3d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
random_arr=np.random.random((2,2))
print(random_arr)


[[0.95451941 0.32108859]
 [0.90405714 0.96037909]]


In [12]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
range_arr=np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [14]:
arr=np.array([[1,2,3], [4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("dimensions:",arr.ndim)



Shape: (2, 3)
Size: 6
Data Type: int32
dimensions: 2


In [17]:
arr=np.array([[1,2,3], [4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("dimensions:",arr.ndim)
print(arr)
arr1=arr[:,1:]
print(arr1)

Shape: (2, 3)
Size: 6
Data Type: int32
dimensions: 2
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [19]:
list1=[1,2,3,4]
list2=[5,6,7,8]
list=[a + b for a, b in zip(list1, list2)]
print(list)

[6, 8, 10, 12]


In [20]:
#arithmetic operator
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a*2)

[5 7 9]
[ 4 10 18]
[2 4 6]


In [21]:
mat1=np.array([[1,2], [3,4]])
mat2=np.array([[5,6], [7,8]])
result=np.dot(mat1,mat2)
print(result)

[[19 22]
 [43 50]]


In [22]:
#broadcasting
a=np.array([1,2,3])
b=8
print(a+b)


[ 9 10 11]


In [24]:
#universal funtions
arr=np.array([1,2,3])
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [25]:
arr=np.array([1,2,3])
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

Sum: 6
Mean: 2.0
Standard Deviation: 0.816496580927726
Max: 3
Min: 1


In [26]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [27]:
#stacking
a=np.array([1,2])
b=np.array([4,5])
print(np.vstack((a,b)))
print(np.hstack((a,b)))



[[1 2]
 [4 5]]
[1 2 4 5]


In [29]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr) #view shares memory

copy=arr.copy()
copy[0]=10   #shares memory
print(arr)

[10  2  3]
[10  2  3]


In [36]:
arr = np.arange(10, 51,10)
print(arr)

[10 20 30 40 50]


In [37]:
arr = np.random.rand(3, 3)
print(arr)

[[0.16275034 0.17639546 0.76725053]
 [0.91698403 0.47182894 0.06206232]
 [0.11996846 0.61731601 0.64673012]]


In [38]:
arr = np.random.rand(3, 3)
print(arr)
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

[[0.80173502 0.89877144 0.63887478]
 [0.01829161 0.37067057 0.76380165]
 [0.29035175 0.52353277 0.54550808]]
Sum: 4.8515376552614375
Mean: 0.5390597394734931
Standard Deviation: 0.2625844756240852
Max: 0.8987714360040713
Min: 0.01829161252436473


In [39]:
a=np.array([1,8,9])
b=5
print(a+b)


[ 6 13 14]


In [40]:
mat1=np.array([[3,8], [9,6]])
mat2=np.array([[5,6], [7,8]])
result=np.dot(mat1,mat2)
print(result)

[[ 71  82]
 [ 87 102]]


In [53]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)
first_row = arr[0]
print("The first row is ",first_row)
last_col=arr[:,-1]
print("The last column is:",last_col)
subarray=arr[0:3]
print("The subarray is:",subarray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
The first row is  [1 2 3 4 5]
The last column is: [ 5 10 15 20 25]
The subarray is: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
